FROM node:alpine as builder

# 设置环境变量
ENV PROJECT_ENV production
ENV NODE_ENV node

# 缓存node_modules
COPY package*.json /app/

# 工作目录
WORKDIR /app

# 安装依赖
RUN npm install -registry=https://registry.npm.taobao.org

# 拷贝源代码到工作目录
COPY . /app

# 打包
RUN npm run build

# 选择nginx基础镜像运行程序
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/docs/.vuepress/dist  /app/docs/.vuepress/dist